spring.application.name=url-shortner-sb
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortenerdb
spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
#will update the schema i.e adds existing columns without removing existing ones
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=1181d915cfa85fea72ebcc32f90167386252ad1c2a9d21be220f1eda599fcad127f2ea9fbdde336dbc627d3302ecbc911921de33827161dbe8aafa39bc9d2a04
jwt.expiration=172800000

logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortner=DEBUG